environment:
  GITHUB_TOKEN: ENCRYPTED[9c298cd7d8c2c90c3b3b7bf53545b09acc86d25b70d2d4eb98d4b9e711be01c57bb6bd55913682fcb234c1f5946a1653]
  TOKEN: ENCRYPTED[885028d10057122b33e25916801cdaa66033fbc384867b3e9543478ac7628509a5fc7f8d7244905c8b03726d1ced4c6b]

inefficient_task:
  container:
    image: xealea/xea:01
    platform: linux
    cpu: 8
    memory: 32G
  build_script:
    - export token=$TOKEN
    - git clone --depth=1 https://github.com/xealea/linux.git
    - cd linux
    - curl -s https://raw.githubusercontent.com/xealea/builder-kernel-x86/nusantara/debpkg | bash